set x = WScript.CreateObject("WScript.Shell")
x.Run "https://www.netflix.com/title/80050008"
WScript.Sleep 10000
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{ENTER}"
WScript.Sleep 5000
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "alec.n.herold@intel.com"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "Q12022intel$444"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{ENTER}"
WScript.Sleep 10000
x.SendKeys "^{R}"
WScript.Sleep 10000
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{ENTER}"
WScript.Sleep 10000
x.SendKeys "^l"
WScript.Sleep 500
x.SendKeys "^l"
WScript.Sleep 1000
x.SendKeys "%{TAB}"
WScript.Sleep 500
x.SendKeys "%{TAB}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 1000
x.SendKeys "{ENTER}"
WScript.Sleep 7000
x.SendKeys "f"
WScript.Sleep 5000
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{LEFT 250}"
WScript.Sleep 500
x.SendKeys "{ENTER}"






