set x = WScript.CreateObject("WScript.Shell")
x.SendKeys  "^{ESC}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 1000
x.SendKeys "{RIGHT}"
x.SendKeys "{RIGHT}"
x.SendKeys "{RIGHT}"
x.SendKeys "{RIGHT}"
x.SendKeys "{RIGHT}"
x.SendKeys "{ENTER}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 50
x.SendKeys "{TAB}"
WScript.Sleep 50
x.SendKeys "{TAB}"
WScript.Sleep 50
x.SendKeys "{TAB}"
WScript.Sleep 50
x.SendKeys "{TAB}"
WScript.Sleep 50
x.SendKeys "{TAB}"
WScript.Sleep 50
x.SendKeys "{DOWN}"
WScript.Sleep 50
x.SendKeys "{DOWN}"
WScript.Sleep 50
x.SendKeys "{DOWN}"
WScript.Sleep 50
x.SendKeys "{DOWN}"
WScript.Sleep 50
x.SendKeys "{ENTER}"
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 50
x.SendKeys "{TAB}"
WScript.Sleep 50
x.SendKeys "{TAB}"
WScript.Sleep 50
x.SendKeys "{TAB}"
WScript.Sleep 50
x.SendKeys "{TAB}"
WScript.Sleep 50
x.SendKeys "{TAB}"
WScript.Sleep 50
x.SendKeys "{ENTER}"
WScript.Sleep 50
x.SendKeys "{DOWN}"
WScript.Sleep 50
x.SendKeys "{DOWN}"
WScript.Sleep 50
x.SendKeys "{ENTER}"
WScript.Sleep 50
x.SendKeys  "%{F4}"