set x = WScript.CreateObject("WScript.Shell")
WScript.Sleep 10000
x.SendKeys  "{TAB}"
WScript.Sleep 1000
x.SendKeys  "80b168a2d1725e17778f5e340"
WScript.Sleep 1000
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 1000
x.SendKeys  "{ENTER}"
WScript.Sleep 500
x.SendKeys  "{ENTER}"
WScript.Sleep 1000
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{ENTER}"
WScript.Sleep 1000
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{ENTER}"
WScript.Sleep 1000
x.SendKeys  "MobileMark25"
WScript.Sleep 1000
x.SendKeys  "{ENTER}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  " "
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  " "
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{TAB}"
WScript.Sleep 500
x.SendKeys  "{ENTER}"
WScript.Sleep 1000
x.SendKeys  "{ENTER}"
WScript.Sleep 1000
x.SendKeys  "%{F4}"


