set x = WScript.CreateObject("WScript.Shell")
x.SendKeys  "^{ESC}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{RIGHT}"
WScript.Sleep 500
x.SendKeys "{RIGHT}"
WScript.Sleep 500
x.SendKeys "{RIGHT}"
WScript.Sleep 500
x.SendKeys "{RIGHT}"
WScript.Sleep 500
x.SendKeys "{RIGHT}"
WScript.Sleep 100
x.SendKeys "{ENTER}"
WScript.Sleep 2000
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{DOWN}"
WScript.Sleep 500
x.SendKeys "{DOWN}"
WScript.Sleep 500
x.SendKeys "{DOWN}"
WScript.Sleep 500
x.SendKeys "{DOWN}"
WScript.Sleep 500
x.SendKeys "{ENTER}"
WScript.Sleep 2000
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{ENTER}"
WScript.Sleep 500
x.SendKeys "{UP}"
WScript.Sleep 500
x.SendKeys "{UP}"
WScript.Sleep 500
x.SendKeys "{ENTER}"
WScript.Sleep 500
x.SendKeys  "%{F4}"