set x = WScript.CreateObject("WScript.Shell")
x.SendKeys "^{ESCAPE}"
WScript.Sleep 2000
x.SendKeys "Security and"
WScript.Sleep 5000
x.SendKeys "{ENTER}"
WScript.Sleep 2000
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{DOWN}"
WScript.Sleep 500
x.SendKeys "{ENTER}"
WScript.Sleep 5000
x.SendKeys "{DOWN}"
WScript.Sleep 200
x.SendKeys "!c-"
WScript.Sleep 200
x.SendKeys "{DOWN}"
WScript.Sleep 200
x.SendKeys "!c-"
WScript.Sleep 200
x.SendKeys "{DOWN}"
WScript.Sleep 200
x.SendKeys "!c-"
WScript.Sleep 200
x.SendKeys "{DOWN}"
WScript.Sleep 200
x.SendKeys "!c-"
WScript.Sleep 200
x.SendKeys "{DOWN}"
WScript.Sleep 200
x.SendKeys "!c-"
WScript.Sleep 200
x.SendKeys "{RIGHT}"
WScript.Sleep 200
x.SendKeys "{DOWN}"
WScript.Sleep 200
x.SendKeys "{DOWN}"
WScript.Sleep 200
x.SendKeys "!c-"
WScript.Sleep 200
x.SendKeys "{UP}"
WScript.Sleep 200
x.SendKeys "!c-"
WScript.Sleep 200
x.SendKeys "{UP}"
WScript.Sleep 200
x.SendKeys "!c-"
WScript.Sleep 200
x.SendKeys "{UP}"
WScript.Sleep 200
x.SendKeys "!c-"
WScript.Sleep 200
x.SendKeys "{UP}"
WScript.Sleep 200
x.SendKeys "!c-"
WScript.Sleep 200
x.SendKeys "{UP}"
WScript.Sleep 200
x.SendKeys "!c-"
WScript.Sleep 200
x.SendKeys "{DOWN}"
WScript.Sleep 200
x.SendKeys "{DOWN}"
WScript.Sleep 200
x.SendKeys "{DOWN}"
WScript.Sleep 200
x.SendKeys "{DOWN}"
WScript.Sleep 200
x.SendKeys "{DOWN}"
WScript.Sleep 200
x.SendKeys "{TAB}"
WScript.Sleep 200
x.SendKeys "{ENTER}"
WScript.Sleep 500
x.SendKeys "%{F4}"
WScript.Sleep 2000
x.SendKeys "^{ESCAPE}"
WScript.Sleep 2000
x.SendKeys "Noti"
WScript.Sleep 1000
x.SendKeys "{ENTER}"
WScript.Sleep 5000
x.SendKeys " "
WScript.Sleep 1000
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys " "
WScript.Sleep 500
x.SendKeys "{TAB}"
WScript.Sleep 500
x.SendKeys "%{F4}"